package com.sungfamilyadmin.constants;

public class Constant
{

    public static final String RECIPIENT_FB_TOKEN = "dgHJRroA1js:APA91bGVEkq2vTs3uCeNbu_AlpUbuvKJm7hCE8n4abSmvwIbIlDg1GTrVBe1PtSFOaBIl9KKqP2KEOGYLR9fdxRPcQcwvBgwERcH2z3kj4aK4eemZUVDh0iHwFSCdN6W2GvV6DF95txu";

    public static final String [] SAMPLE_REVIEWS = {
            "You can get some favorite drink items at a substantial discount.",
            "Love pepsi.  Tired of flat pepsi. Thinking about going to coke because of this",
            "I work here. It's great",
            "Little to no parking on the street. 2 spots to park at a gastion near DC. This place is a logistical nightmare and they should be ashamed.",
            "Hit or miss on appointment times",
            "Great place inside and out",
            "Needs more Fizzzz",
            "This place is so slow it took two and a half hours to load a half a load",
            "Great company I love Pepsi products!",
            "Will not return pbone calls regarding business very unprofessional",
            "Thumbs up!",
            "Professional Growth.",
            "Learning Path.",
            "You have to be self motivated. NO ONE will hold your hand and tell you that you're doing a great job. If you need constant affirmations from management, this company isn't for you." ,
            "Stack ranking is a horrible practice since it's rife with favoritism. ",
            "OMG; my hedges never looked this great!  Brandon listens to his customers' request.  He is detail oriented; took time to ensure his work was  completed as I requested.  Brandon left my property picture perfect. ",
            "Lawn Love has been great for me. I was having a difficult time finding someone to mow my lawn. Then I discovered Lawn Love and this has worked out very well for me",
            "High hopes but a huge disappointment.",
            "Strongly recommend! Russell did a great job on the lawn. Looks neat! I will definitely be using this service for a while!",
            "Amazing work and very professional. Thank you.",
            "Demetrius and his team did a great job. The lawn looks awesome. I am happy that they come when they say they are coming. So far my experience with them had been top notch.",
            "I’m really pleased with the service they provide.",
            "Professional/Good price for Service and Brandi" + "Knew exactly the way I wanted my lawn taken care of. Thanks",
            "LOVE LOVE LOVE this service! And my lawn guy! Professional, expert and on time." +
                    "I've kissed enough lawn pro frogs to know.",
            "Scheduled first appointment and their crew never showed up.   Called to discuss with customer service and never received a follow up.   Waste of time... advise looking elsewhere",
            "Bobby, does a Excellent Job he calls when he is enroute and, I would highly recommend him to you anyone who needs lawn care.",
            "Lawn love has been doing my lawn for about 9 months now and they do a fantastic job!",
            "I went to the drive thru and was told to pull around to the side while they make my drink. I waited for 10  minutes before calling the store. Apparently, they forgot about me and had to prepare my drink once I called.....",
            "Staff not very friendly and the music is really loud if you are trying to get any work done (even with noise canceling headphones on).  Parking is also tuff.  Would not recommend for studying.",
            "Great place after run meet up on a Sunday morning.",
            "Waited 30 minutes in drive-thru, and they barely acknowledged wait when I got to the window. Then, I waited forever at the window. Something's going on there!",
            "THE WORST STARBUCKS EVER! Drive thru is so God awful",
            "The staff was very rud.",
            "There are always large house flies in the lobby. I come to this Starbucks regularly to work & always have to kill half a dozen of them or more. I often work in other Starbucks as well and none of the others in this city have this problem.",
            "Nice place maybe not the best but very nice.. I think they could be 5 star I'm just not sure how.",
            "Waited 10.minutes to order.  Last took order and even though I said diet coke she rang up as coke.  She handed me receipt and I again told her diet coke.",
            "This place is a disgrace.  Over the course of 2 weeks visiting, frequently run out of menu items. Exceedingly long lines. They have a captive audience so apparently no incentive to improve. I don't see why NH puts up with it.",
            "I was misdiagnosed with shingles at an urgent care and ended up here as I was in a lot of pain at this point. The staff was friendly and made you feel comfortable, two male nurses were attentive and had good bedside manner.",
            "The staff at the emergency nurse station was rude and speaking of disrespectful personal issues including those Alex life etc. I noticed some of them dancing shaking their hands up in the air saying profanity and praising they were leaving in a few minutes and that they were tired of dealing with the patients",
            "The emergency department is amazing. The nurses and doctors go above and beyond for their patients. And my waiting time wasn't too bad.",
            "I only gave them one star because there isn't an option for no stars. Staff sucks and the food is worst. Thinking of eating here take my advice.....\n" +
                    "DON'T!!!",
            "Poorly managed. Very slow. Frequently get orders wrong. Understaffed",
            "I went to the walk in and they directed me to the ER based on my symptoms. Excellent service to help get me taken care of right away.",
            "It. Is. a. Good. Teaching. Learning. School.",
            "Over the years, I have been truly impressed with my son's school. The teachers are overall professional and HIP at the same time. ",
            "my son loves his school the teachers are polite and real well educated",
            "I went to this school and I would always get sick and the teachers taught badly some of them were good I went there for a year the math is rubbish I would go it's better school and I do",
            "Ill be a freshman soon, and i still wish i went to this school. Best school ever",
            "The school is great. The people that have said these things were mad at the school but I can ashure you that your child should go here.",
            "Westminster is a great school. Everyone here is so supportive and kind. The teachers feel like friends and the friends are always there for you. The education is great as well.",
            "This is the best school. I have made friends here and treat them like family. Coming here is the best thing I ever did.",
            "A place we chose a whim one night to eat with friends. Thoroughly pleased with the menu, food, and service.  We went on a Sunday evening around 7.",
            "1000% recommend!!!! Ask for  Ashina. She'll definitely take care of you and give great service. I've been knowing her for 4 years now & follow her where ever she goes! "
    };

    public static final String [] FIRST_NAMES = {
    "Sophia","Emma","Bronson","Bedegrayne",
            "Bernadette",
            "Billie",
            "Birdee",
            "Bliss",
            "Brice",
            "Brittany",
            "Bryony",
            "Cameo",
            "Carol",
            "Chalee",
            "Christy",
            "Corky",
            "Cotovatre",
            "Courage",
            "Daelen",
            "Dana",
            "Darnell",
            "Dawn",
            "Delsie",
            "Denita",
            "Devon",
            "Devona",
            "Diamond",
            "Divinity",
            "Duff",
            "Dustin",
            "Dusty",
            "Ellen",
            "Eppie",
            "Evelyn",
            "Everilda",
            "Falynn",
            "Fanny",
            "Faren",
            "Freedom",
            "Gala",
            "Galen",
            "Gardenia"
    };
    public static final String [] LAST_NAMES = {
            "Jackson",
            "Alfredo",
            "Ali",
            "Allan",
            "Allen",
            "Alonso",
            "Alonzo",
            "Alphonse",
            "Alphonso",
           " Alton",
            "Alva",
           " Alvaro",
            "Alvin",
            "Amado",
            "Ambrose",
            "Amos",
            "Anderson",
            "Andre",
            "Andrea",
            "Andreas",
            "Andres",
            "Andrew",
            "Andy",
            "Angel",
            "Angelo",
            "Anibal",
            "Anthony",
            "Antione",
            "Antoine",
           " Anton"
    };
}
